spring:
  application:
    name: tenent-services

  data:
    mongodb:
      uri: mongodb://${mongo.user}:${mongo.password}@192.168.1.158:27017/${mongo.DB}?authSource=admin

server:
  port: 8081
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: ON_PARAM

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - mappings
  endpoint:
    health:
      show-details: ALWAYS

info:
  app:
    name: Tenent Services
    description: This service is responsible for managing tenants in the application.
    version: 1.0.0